---
- name: create token in prod cluster to join node
  hosts: all
  become: yes
  tasks:
    - name:  wait for installton to complete
      shell: sleep 120  
    - name:   create token
      shell: kubeadm token create --print-join-command > /tmp/token.sh 
    - name : edit token 
      shell: sed -i 's+kubeadm+sudo kubeadm+' /tmp/token.sh  
    - name : edit token 
      shell: sed -i 's+$+ --cri-socket unix:///var/run/cri-dockerd.sock --ignore-preflight-errors=all+' /tmp/token.sh
    - name: Store token file  
      fetch:
        src: /tmp/token.sh
        dest: /tmp/token.sh        
    - name: install prometheus
      apt: name=prometheus state=present
    - name: config prometheus
      copy: src=prometheus_prod.yml dest=/etc/prometheus/prometheus.yml
    - name: Restart prometheus
      service: name=prometheus state=restarted
